### PR TITLE
feat(search-clear): add search field clear primitive

### PR DESCRIPTION
**Pull request by Mattewn99**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/ng-primitives/ng-primitives/blob/main/CONTRIBUTING.md#-commit-message-guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [X] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation changes
- [ ] Other... Please describe:

## What does this PR implement/fix?

Right now, after clicking on "clear", the button is still visible

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

### CODE REVIEW

**Comment by Mattewn99** [comment]
@ashley-hunter does it maybe make sense to move all the logic about the clear button (I mean also the visibility) inside the directive that at this point could be a `@Component`?

**Comment by ashley-hunter** [comment]
Thank you very much for the contribution @Mattewn99. 

It is interesting that you brought this up as I was recently thinking about this exact thing myself. Ideally the optimal scenario is one that involves the least effort on the consumers part - and what I had thought might be the best solution was to introduce an `NgpSearchFieldClear` primitive that a user could attach to the clear button and it would handle the clearing for them on click. 

This would avoid the need for any JavaScript to be written on the consumers end at all - they wouldn't need to programmatically change state (like they currently do), nor would they need to use ViewChild and call a method on the directive instance. I would be interested in hearing your thoughts on this approach! Thanks again!

**Comment by Mattewn99** [comment]
I also didn't like to always have to write the js part for clearing the input. I like the approach of creating a new `NgpSearchFieldClear` directive. I can try an implementation on this PR. Thanks a lot!

**Comment by ashley-hunter** [comment]
Perfect! Thank you! I believe there should be some guidance on creating a new primitive directive in the contributing guide. If anything isn't clear or you need any help just reach out.

**Comment by Mattewn99** [comment]
@ashley-hunter I pushed an implementation of the new primitive. I'm not sure about the styling but I thought it'd be nice to set it in the primitive so the user doesn't need to add it in the consumer. About the docs would you prefer to have a separate page for this primitive? I added just a small example in the `search-field.example` since I think this is going to be more or less the only use case for this primitive. What do you think? Thanks!

**Comment by ashley-hunter** [comment]
Thank you! Yes, so I think we want primitives to have no styles associated with them - styles would always be defined by the user to give them flexibility and to align with our other components and the idea of being a "Headless" library (in otherwords, no styles). 

We can add a data attribute to the clear button to reflect the empty state of the input field (we do this on the search field already) and the user can show or hide the button however they like - most likely with `display: none`, but for things like animations or transitions this gives most flexibility.

I think we could move the directive into the existing search field folder rather than needing one specific for the clear directive. Apart from that looks great! If you need any help with the above notes, just let me know, Im happy to help get this over the finish line any way you need 😊

**Comment by Mattewn99** [comment]
@ashley-hunter makes sense. I added a `data-empty` attribute 👍🏻

**Comment by Mattewn99** [comment]
Maybe @ashley-hunter it'd be nice to have a slack channel or something similar for faster communication and news on the next features 🤩

**Comment by ashley-hunter** [comment]
Thank you! Yes that's a good idea! It's not my area of expertise, I know I have some groups use Discord - but if there is a good reason to use a specific app I'm open to suggestions!

**Comment by Mattewn99** [comment]
I think discord is also a good option!

**Comment by ashley-hunter** [comment]
Great! Good suggestion, I will set this up tonight 😊

**Comment by ashley-hunter** [comment]
Thank you for your contribution! All looks good!

I have setup a discord server here: https://discord.gg/NTdjc5r3gC, any issues accessing it let me know!

**Comment by ashley-hunter** [comment]
@allcontributors

**Comment by ashley-hunter** [comment]
@allcontributors please add @Mattewn99 for code and doc

**Comment by ashley-hunter** [comment]
@allcontributors please add @Mattewn99 for code and doc

**Pull request merged**
