### PR TITLE
feat(docs): implement dark mode

### PR DESCRIPTION
**Pull request by benjaminforras**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/ng-primitives/ng-primitives/blob/main/CONTRIBUTING.md#-commit-message-guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation changes
- [ ] Other... Please describe:

## Issue

Closes #

## What does this PR implement/fix?

Allows the users to switch between dark/light mode for the documentation site.

- [x] Basic layout changes for dark mode.
- [x] Update examples to be dark mode friendly.
- [x] Update logo

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by ashley-hunter** [comment]
This is really taking shape! Great work!

**Comment by benjaminforras** [comment]
I think I finished with laying down the basics and added dark mode to every example.
Let me know if you find anything or if you'd like me to change something. 

One thing that I'd like to investigate in the future is to have tailwindcss' `@apply` rules in the examples which can be translated to CSS when viewing the source code, if it can't be done, then I'll try to sync up the color codes to match tailwind's better. For now I think it's a solid base to iterate on.

**Comment by ashley-hunter** [comment]
This is excellent! Docs look super nice in dark mode! Literally the only thing I notice which should hopefully be a quick fix:

image

The inline code snippets I think might be better dark - probably the same as the type `T` shown in the screenshot after `ngpAccordionItemValue`.

I wonder would the red text also be slightly better in a slightly brighter red color? I've also outlined that in the screenshot above, the same color is used in the left nav:

image

And above the header:

image

Apart from that, this is a superb enhancement, thank you very much for your contribution! Really great work!

**Comment by benjaminforras** [comment]
Thanks for the feedback, I'll fix those as soon as I have some time again.

**Comment by ashley-hunter** [comment]
No problem! No rush, I really appreciate the hard work and effort you have put in 😊!

**Comment by ashley-hunter** [comment]
> One thing that I'd like to investigate in the future is to have tailwindcss' @apply rules in the examples which can be translated to CSS when viewing the source code so the users copy to pure css code, if it can't be done, then I'll try to sync up the color codes to match tailwind's better. For now I think it's a solid base to iterate on.

It's interesting you mention this, I was thinking something similar - its certainly a possibility, and something we can look into in future, but as you say, this is an excellent start, and even if we persist with this approach indefinitely I still think it's not a bad one!

**Comment by benjaminforras** [comment]
Updated the code with the changes requested. Not sure about the lighter red colors, I've made them 20% lighter.
Also I extracted these colors to css variables so it's easier to change in the future.

**Review by ashley-hunter — APPROVED** [review]
This is perfect, thank you! I'll do a release later today and make this available to everyone! Thanks for such an excellent contribution!

**Comment by ashley-hunter** [comment]
@allcontributors please add @benjaminforras for code, ideas and doc

**Pull request merged**
